cd C:\Users\krzys\OneDrive\Pulpit\football_page
mkdir -p .github/workflows
cat > .github/workflows/ci.yml <<EOF
name: CI/CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'
      - name: Cache Maven repo
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      - run: mvn clean verify --batch-mode
      - run: mvn checkstyle:check --batch-mode
      - run: mvn spotbugs:check --batch-mode
EOF
